In [1]:
import numpy as np

In [2]:
# ------------------------------ eye method demo ----------------------------- #
m1 = np.eye(N=3,M=3, k=1)
print(m1)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


## Slice NDim arrays

In [3]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# indexing
arr2d[1,2]

6

In [7]:
# slicing
arr2d[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr2d[0::2, 1:]

array([[2, 3],
       [8, 9]])

In [12]:
arr2d[0::2, 0::2]

array([[1, 3],
       [7, 9]])

In [14]:
arr3d = np.arange(1,19).reshape(2,3,3)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
arr3d[0,1,1]

5

In [18]:
arr3d[:,0,:]

array([[ 1,  2,  3],
       [10, 11, 12]])

In [19]:
arr3d[:,0,::2]

array([[ 1,  3],
       [10, 12]])